- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  tasks:
    - name: Update Apt:
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
    - import_tasks: tasks/ssh.yaml
    - import_tasks: tasks/nvim.yaml
    - import_tasks: tasks/dotfiles.yaml
    - import_tasks: tasks/git-config.yaml
    - import_tasks: tasks/tools.yaml
