- name: Install stow
  ansible.builtin.apt:
    name: stow
  tags:
    - install
    - dotfiles
    - stow
- name: Remove dotfiles
  ansible.builtin.file:
    path: ~/.dotfiles
    state: absent
  tags:
    - install
    - dotfiles
    - clean
- name: Clone dotfiles
  ansible.builtin.git:
    repo: "git@github.com:ethanholz/config_files.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow

