- name: Install stow and zsh
  ansible.builtin.apt:
    pkg: 
     - stow
     - zsh
  become: true
  tags:
    - install
    - dotfiles
    - zsh
    - stow
- name: Remove dotfiles
  ansible.builtin.file:
    path: ~/.dotfiles
    state: absent
  tags:
    - install
    - dotfiles
    - clean
- name: Clone dotfiles
  ansible.builtin.git:
    repo: "git@github.com:ethanholz/config_files.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Install zsh dotfile
  ansible.builtin.shell: cd {{ lookup('env', 'HOME') }}/.dotfiles && stow zsh
  tags:
    - install
    - stow
    - zsh
- name: Change to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true

