- name: Install rustup
  ansible.builtin.shell: curl https://sh.rustup.rs -sSf | sh
  tags:
    - install
    - tools
    - rust
- name: Install apt packages
  ansible.builtin.apt:
    pkg:
      - zoxide
      - tmux
      - zsh
      - fzf
  tags:
    - install
    - tools
- name: Install starship.rs
  ansible.builtin.shell: curl -sS https://starship.rs/install.sh | sh
  tags:
    - install
    - tools
- name: Install Alacritty
  block:
    - Name: Install Alacritty
      ansible.builtin.shell: cargo install alacritty
  tags:
    - install
    - tools
    - terminal
- name: Remove installed go version
  ansible.builtin.file:
    path: /usr/local/go
    state: absent
  become: true
  tags:
    - golang
    - install
    - clean
- name: Install go
  block:
    - name: Download go 1.18.3
      ansible.builtin.get_url:
        url: https://go.dev/dl/go1.18.3.linux-amd64.tar.gz
        dest: /tmp/go1.18.3.tar.gz
    - name: Install go 1.18.3
      ansible.builtin.unarchive:
        src: /tmp/go1.18.3.tar.gz
        dest: /usr/local
      become: true
  tags:
    - golang
    - install
