- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes
- name: Install rustup
  block:
    - name: Download Installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
    - name: install rust/cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y
      become: True
  tags:
    - rust
    - tools
    - install
- name: Install apt dev tools packages
  ansible.builtin.apt:
    pkg:
      - zoxide
      - tmux
      - fzf
  tags:
    - install
    - tools
- name: Install starship.rs
  ansible.builtin.shell: curl -sS https://starship.rs/install.sh | sh
  tags:
    - install
    - tools
- name: Install Alacritty
  block:
    - name: Install Alacritty
      ansible.builtin.shell: cargo install alacritty
  tags:
    - install
    - tools
    - terminal
- name: Remove installed go version
  ansible.builtin.file:
    path: /usr/local/go
    state: absent
  become: true
  tags:
    - golang
    - install
    - clean
- name: Install go
  block:
    - name: Download go 1.18.3
      ansible.builtin.get_url:
        url: https://go.dev/dl/go1.18.3.linux-amd64.tar.gz
        dest: /tmp/go1.18.3.tar.gz
    - name: Install go 1.18.3
      ansible.builtin.unarchive:
        src: /tmp/go1.18.3.tar.gz
        dest: /usr/local
      become: true
  tags:
    - golang
    - install
